<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Remembers the answer given to a write, so asking again gets the same
 * answer instead of doing it twice.
 *
 * A till that sold while offline replays those sales when the connection
 * returns. Replays are not rare edge cases — a dropped response, a retry,
 * a device syncing twice — and without this every one of them would be a
 * second sale, a second payment, a second stock movement.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('idempotency_keys', function (Blueprint $table) {
            $table->id();
            // Generated by the device, unique across the whole platform.
            $table->uuid('key')->unique();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->unsignedBigInteger('tenant_id')->nullable()->index();
            $table->string('method', 10);
            $table->string('path');
            // The same key sent with a different body is a client bug, not a
            // replay, and must not silently return the first answer.
            $table->string('request_fingerprint', 64);
            $table->unsignedSmallInteger('response_status')->nullable();
            $table->longText('response_body')->nullable();
            $table->timestamps();

            $table->index('created_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('idempotency_keys');
    }
};
