- name: Run Laravel Commands
  uses: appleboy/ssh-action@v1.2.0
  with:
    host: ${{ secrets.HOSTINGER_SSH_HOST }}
    username: ${{ secrets.HOSTINGER_SSH_USER }}
    key: ${{ secrets.HOSTINGER_SSH_KEY }}
    port: ${{ secrets.HOSTINGER_SSH_PORT }}
    script: |
      cd ${{ secrets.HOSTINGER_APP_PATH }}

      echo "Using PHP:"
      /opt/alt/php84/usr/bin/php -v

      /opt/alt/php84/usr/bin/php /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction

      /opt/alt/php84/usr/bin/php artisan migrate --force

      /opt/alt/php84/usr/bin/php artisan optimize:clear

      /opt/alt/php84/usr/bin/php artisan config:cache

      /opt/alt/php84/usr/bin/php artisan route:cache

      /opt/alt/php84/usr/bin/php artisan view:cache
